stages:
  - static_analysis
  - build
  - dynamic_analysis
  

static_analysis:
  stage: static_analysis
  image: python:3.12
  script:
    - pip install semgrep==1.89
    - semgrep --config auto . --json > semgrep-report.json
    - echo "Первая часть статического анализа завершена"
  artifacts:
    paths:
      - semgrep-report.json

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker run --name dvna -p 9090:9090 -d appsecco/dvna:sqlite
    - echo "Сборка прошла успешно"

dynamic_analysis:
  stage: dynamic_analysis
  image: ghcr.io/zaproxy/zaproxy:latest
  dependencies:
    - build
  services:
    - name: docker:dind
      alias: docker
  script:
    - mkdir /zap/wrk
    - zap-full-scan.py -t "http://dvna:9090" -x zap.xml
    - mv /zap/wrk/zap.xml zap.xml
    - echo "Динамический анализ с использованием zap завершён"
  artifacts:
    paths:
      - zap.xml


